version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
     MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
     MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
volumes:
  db: